### ISSUE TITLE
Broken with firmware update...but...I've fixed it.

### ISSUE THREAD

**Issue by ancker010** [iandees/netgear-scrapers#4]
This is broken by the latest firmware update for the CM1100 modem. Mediacom cable randomly upgraded me from V2.01.02 to V7.01.01.
The login method switches from http basic auth to an html form.

I've already fixed this in my local fork, but it needs to be polished a bit before I submit a PR.
My version uses environmental variables to pass it the InfluxDB info and user/pass. I'll add a way to specify which version of auth is required for someone's particular modem.

**Comment by iandees** [comment]
Thanks for reporting and looking into it! My modem got upgraded, too.

Feel free to adjust how InfluxDB parameters get passed in.
